name: 'Label Trigger'

on:
  pull_request:
    types: [labeled]
jobs:
  gcp-pull-request-ci:
    if: github.event.review.state == 'approved'
    uses: posigensolar/github-actions/.github/workflows/gcp-label-ci.yaml@master
    with:
      repository: ${{ github.repository }}
      deploy-prod: ${{ contains( github.event.pull_request.labels.*.name, 'deploy-prd') }}
      pull-request-number: ${{ github.event.pull_request.number }}
      stg-env: 'stg'
      prd-env: 'prd'
    secrets:
      STG_GOOGLE_CREDENTIALS: ${{ secrets.STG_GOOGLE_CREDENTIALS }}     
      PRD_GOOGLE_CREDENTIALS: ${{ secrets.PRD_GOOGLE_CREDENTIALS }}
      token: ${{ github.token }}
      stg-projectId: ${{ secrets.STG_GCP_PROJECT_ID }} 
      stg-cli-args: ${{ secrets.STG_GCP_CLI_ARGS }}
      prd-projectId: ${{ secrets.PRD_GCP_PROJECT_ID }} 
      prd-cli-args: ${{ secrets.PRD_GCP_CLI_ARGS }}